### PR TITLE
Enhancement: validate webhook url

### PR DESCRIPTION
**Pull request by minademian**
Resolves issue #26 

Added a function to `app.listen()` in server.js to check that the webhook URL is reachable and working properly.

### CODE REVIEW

**Comment by joshuasorkin** [comment]
This is cool!  Successfully identified a working and non-working webhook URL when I tested locally :)

Question about the error response:

```
if (res.ok) {
            console.log(`Webhook URL configured properly!`);
            data = true;
            return res;
          } else result.send(errMsg);
```

Because we're using `result.send(errMsg)` instead of another `throw new Error(errMsg)`, the `app.listen()` startup flow will continue even if the webhook url is non-functional.  Was that your intention?

**Comment by minademian** [comment]
> This is cool! Successfully identified a working and non-working webhook URL when I tested locally :)
> 
> Question about the error response:
> 
> ```
> if (res.ok) {
>             console.log(`Webhook URL configured properly!`);
>             data = true;
>             return res;
>           } else result.send(errMsg);
> ```
> 
> Because we're using `result.send(errMsg)` instead of another `throw new Error(errMsg)`, the `app.listen()` startup flow will continue even if the webhook url is non-functional. Was that your intention?

I did consider that, I went with result.send because it’s less 'final'. But throwing an Error and killing the application flow seems like a better solution. Will change this and commit a change.

**Comment by minademian** [comment]
> throw new Error(errMsg)

@joshuasorkin change made. approve if you’re happy with everything else.

**Comment by joshuasorkin** [comment]
good stuff

**Pull request merged**
