### PR TITLE
Chore: configure turning request validation off for local development

### PR DESCRIPTION
**Pull request by minademian**
Resolves issue #26 

To test this PR:

```shell
$ npm i # to install new pkg
$ npm run watch
```

Run the phone call flow and you shouldn’t get the 403 error in Twilio.

### CODE REVIEW

**Comment by joshuasorkin** [comment]
duplicate declaration of `app` in `server.js` at lines 32 and 51

**Comment by minademian** [comment]
> duplicate declaration of `app` in `server.js` at lines 32 and 51

Nice catch. Shall fix.

**Comment by minademian** [comment]
> > duplicate declaration of `app` in `server.js` at lines 32 and 51
> 
> Nice catch. Shall fix.

@joshuasorkin fixed. approve if you’re happy with everything else.

**Review by joshuasorkin — DISMISSED** [review]
I tested a GET request by running both of these in the Chrome address bar: `http://localhost:1337/conferenceAnnounceEnd_participantLeave`
`http://localhost:1337/processAutomatic`

Got this response:
`No signature header error - X-Twilio-Signature header does not exist, maybe this request is not coming from Twilio.`

**Comment by minademian** [comment]
> I tested a GET request by running both of these in the Chrome address bar: `http://localhost:1337/conferenceAnnounceEnd_participantLeave` `http://localhost:1337/processAutomatic`
> 
> Got this response: `No signature header error - X-Twilio-Signature header does not exist, maybe this request is not coming from Twilio.`

Got a different error when I tested this endpoint, it’s complaining about a JSON error. Were you testing this while on this PR’s branch?
Also, some of these endpoints can’t be tested from the browser or Postman. Best to test them through the phone call or SMS flow.

**Comment by joshuasorkin** [comment]
ok, yeah, i think not checking out the branch once I fetched it was causing the problems I saw.

replicated your JSON error.

I'm with you on needing to test the POST endpoints using Postman or curl, but the GET endpoints should be accessible by submitting the URL through the browser like with any typical REST GET.  granted they might not have the required parameters, but that needs to be part of our error handling anyways.

**Comment by joshuasorkin** [comment]
the ones that are normally reached via Twilio webhooks should return a block of TwiML to the browser, eg

```
<Dial>
+18189991337
</Dial>
```

**Comment by minademian** [comment]
> ok, yeah, i think not checking out the branch once I fetched it was causing the problems I saw.
> 
> replicated your JSON error.
> 
> I'm with you on needing to test the POST endpoints using Postman or curl, but the GET endpoints should be accessible by submitting the URL through the browser like with any typical REST GET. granted they might not have the required parameters, but that needs to be part of our error handling anyways.

@joshuasorkin 
Right. I debugged this, req.query["parameters"] is undefined when I tested with a GET endpoint and it’s expecting `X-Twilio-Signature` to be set.

I think that the error handling would be better handled in a separate PR, so that this one doesn’t become too large. In that separate one, we would look at error handling and a refactor of the setting of headers/query parameters.

**Comment by joshuasorkin** [comment]
Ok now I'm getting that `X-Twilio-Signature` validation error again (i checked to make sure that I was on the right branch this time) on GET requests that have a `shouldValidate` parameter, e.g.

`http://localhost:1337/processGatherConferenceMinutes`
`http://localhost:1337/process_postConferenceIVR`

also, noticed that some of the endpoints still have `twilio.webhook()` instead of `shouldValidate`, e.g.:

`app.get("/endConference_update", twilio.webhook(), function (req, res) {`

 Did you choose to leave those specifically as-is?  If not, we should add an issue for updating the rest of the endpoints.

**Comment by minademian** [comment]
> Ok now I'm getting that `X-Twilio-Signature` validation error again (i checked to make sure that I was on the right branch this time) on GET requests that have a `shouldValidate` parameter, e.g.
> 
> `http://localhost:1337/processGatherConferenceMinutes` `http://localhost:1337/process_postConferenceIVR`
> 
> also, noticed that some of the endpoints still have `twilio.webhook()` instead of `shouldValidate`, e.g.:
> 
> `app.get("/endConference_update", twilio.webhook(), function (req, res) {`
> 
> Did you choose to leave those specifically as-is? If not, we should add an issue for updating the rest of the endpoints.

Investigated. The rebase on production after adding the Swagger documentation wrote over the `shouldValidate` variable in all endpoints. Will push them up now.

**Comment by minademian** [comment]
@joshuasorkin check again.

**Pull request merged**
