### PR TITLE
Revert "Sequelize package json fix"

### PR DESCRIPTION
**Pull request by minademian**
Reverts joshuasorkin/vent-taskrouter#16

### CODE REVIEW

**Comment by joshuasorkin** [comment]
Tbh I'm getting a little confused as to what should be done here (revert #16? merge #25? don't revert?) Much as I would love to push ahead on construction, I'm going to hold off for the moment, and we can make a well-informed decision on our call tomorrow.

**Comment by minademian** [comment]
GitHub will take care of it all. A revert commit just removes a previously merged PR and commits it to git history. If you approve and merge, you're all set.

**Comment by joshuasorkin** [comment]
ok then I think I'll merge this one and then we can disregard #25 since it's mostly redundant with this one

**Comment by minademian** [comment]
Alright, sounds good

**Comment by joshuasorkin** [comment]
....oh wait i'm confused.  if I confirm merge on this one, am i confirming the revert, or am I committing #16?

**Comment by minademian** [comment]
If you confirm merge on this one, you're confirming the revert which is essentially rolling back from merging #16.

**Comment by joshuasorkin** [comment]
ok so if I do nothing with this one, the changes from #16 will stay?  That's what I want, assuming you're ok with #16 not being a tagged PR.

**Comment by minademian** [comment]
Yeah, exactly. Cool. That's fine, I can live with untagged PRs.

**Pull request closed without merging**
